spring:
  application:
    name: "core-system"
  datasource:
    username: root
    password: "!Sosad12345"
    url: "jdbc:mysql://localhost:3306/core_system"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop #dev only

  app:
    jwtSecret: "test123456###"
    jwtExpirationMs: 36000