spring:
  application:
    name: "core-system"
  datasource:
    username: root
    password: "!Sosad12345"
    url: "jdbc:mysql://localhost:3306/core_system"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #dev only

  app:
    jwtSecret: "5f0JbGq+K9gR5I4j0s3h8Lf4N5E8D1pklq2PRQz2b5E="
    jwtExpirationMs: 36000