
POST localhost:8080/v1/transactions/top-up
Content-Type: application/json

{
  "userID": "nerd012456",
  "acctNo": "121100585010",
  "topUpBalance": "1000000",
  "rcvAcct": "121100585010",
  "reasons":"Invest"
}

###

POST localhost:8080/v1/transactions/top-up
Content-Type: application/json

{
"userID": "nerd012456",
"acctNo": "121100585010",
"topUpBalance": "500",
"rcvAcct": "121179051263",
"reasons":"Invest"
}
